name: Sync Releases

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: '源仓库 (owner/repo)'
        required: true
        default: 'OpenListTeam/musl-compilers'
      tag:
        description: 'Release 标签'
        required: true
        default: 'latest'

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
    - name: Download Release Assets
      uses: svenstaro/download-release-action@v2
      with:
        repository: ${{ github.event.inputs.source_repo }}
        tag: ${{ github.event.inputs.tag }}
        out: ./downloaded-assets

    - name: List Downloaded Files
      run: ls -la ./downloaded-assets

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: ./downloaded-assets/*
        body: |
          从 ${{ github.event.inputs.source_repo }} 自动同步的 Release
          源标签: ${{ github.event.inputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}